services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/app/data
      - backend-uploads:/app/uploads
    environment:
      - DB_PATH=/app/data/app.db
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
volumes:
  backend-data: {}
  backend-uploads: {}
